#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3"

volumes:
    static-files:
    
    
services:
    db:
        image: postgres:9.6
        volumes:
            - /opt/viewtracker/psql:/var/lib/postgresql/data/pgdata
        env_file:
            - ./config/environment/development.env

    webserver:
        build:
            context: .
            dockerfile: services/webserver/Dockerfile
        ports:
            - "8080:8080"
            - "443:443"
        depends_on:
            - webapp
        volumes:
            - static-files:/srv/static-files
        env_file:
            - ./config/environment/development.env

    webapp:
        build:
            context: webapp
        volumes:
            - ./webapp/viewtracker:/srv/viewtracker
            - static-files:/srv/static-files
        expose:
            - "8080"
        depends_on:
            - db
        env_file:
            - ./config/environment/development.env
